//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bibl.Connect
{
    using System;
    using System.Collections.Generic;
    
    public partial class BookVidacha
    {
        public int ID { get; set; }
        public Nullable<int> SubscriptionID { get; set; }
        public Nullable<int> BookID { get; set; }
        public Nullable<System.DateTime> LoanDate { get; set; }
        public Nullable<System.DateTime> ReturnDate { get; set; }
        public Nullable<int> EmployeeID { get; set; }
    
        public virtual Abonement Abonement { get; set; }
        public virtual Books Books { get; set; }
        public virtual Employees Employees { get; set; }
    }
}
